name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '45 11  *  *  4'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          - "2.7"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install -U pip
      - run: python -m pip install -U setuptools
      - run: python -m pip install setuptools wheel flake8 twine
      - run: python -m pip install coverage coveralls

      - run: python setup.py sdist bdist_wheel
      - run: python -m pip install dist/*.whl

      - run: twine check dist/*
      - run: flake8

      - run: coverage run --source=minrpc -p test/test_rpc.py -v

      - run: coverage combine
      - run: coveralls
        if: env.COVERALLS_REPO_TOKEN != ''
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Publish PyPI package
        if: startsWith(github.ref, 'refs/tags/') &&
            matrix.os == 'ubuntu-latest' &&
            matrix.python == '3.8'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*.whl dist/*.tar.gz
